### ISSUE TITLE
Right click

### ISSUE THREAD

**Issue by bajki** [guixianleng/vue-draggable-tree#2]
How to use this with vuetify context menu when you right click on dragnode. 

Or how to add something to edit or delete node.

**Comment by guixianleng** [comment]
> How to use this with vuetify context menu when you right click on dragnode.
> 
> Or how to add something to edit or delete node.

you can fork the lib and  add the features by yourself

**Comment by bajki** [comment]
I ended up doing that. 

Did you think how to sort order of tree?
